-- 003-add-event-seq.sql
-- Add a monotonic identity column to merchant_payment_events to provide a DB-native
-- monotonic sequence usable as a deterministic tie-break when event_time is equal.
BEGIN;

ALTER TABLE merchant_payment_events
  ADD COLUMN IF NOT EXISTS event_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS merchant_payment_events_event_seq_idx
  ON merchant_payment_events (event_seq);

COMMIT;
